apiVersion: v1
kind: ConfigMap 
metadata:
  name: {{ template "artifactory.fullname" . }}
  labels:
    app: {{ template "artifactory.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.artifactory.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  ready_probe.sh: |
    #!/bin/bash
   
    DONE_FLAG="/opt/jfrog/artifactory/init-success-flag"
    ORIGINAL_DEFAULt_REPOSITORY="example-repo-local"

    curl --connect-timeout 2 localhost:8081/artifactory/webapp/#/login
    if [[ $? -eq 0 ]]; then
      if [[ ! -e $DONE_FLAG ]]; then
        status_code=`curl -o /dev/null -s -w %{http_code}  -X POST -u admin:password -H "Content-type: application/json" -d "{ \"userName\" : \"admin\", \"oldPassword\" : \"password\", \"newPassword1\" : \"$NEW_INIT_PASSWORD\", \"newPassword2\" : \"$NEW_INIT_PASSWORD\" }" http://localhost:8081/artifactory/api/security/users/authorization/changePassword`
        if [[ ${status_code} -ne 200 ]]; then
          echo "Not Up"
          exit 1;
        fi

        sleep 3
        status_code=`curl -o /dev/null -s -w %{http_code} http://localhost:8081/artifactory/api/repositories/$DEFAULT_REPOSITORY_KEY`
        if [[ ${status_code} -ne 200 ]]; then
          curl -X PUT -u admin:$NEW_INIT_PASSWORD -H "Content-type: application/json" -d "{\"key\": \"$DEFAULT_REPOSITORY_KEY\", \"rclass\":\"$DEFAULT_REPOSITORY_CLASS\", \"packageType\": \"$DEFAULT_REPOSITORY_TYPE\", \"repoLayoutRef\": \"$DEFAULT_REPOSITORY_LAYOUT\"}" http://localhost:8081/artifactory/api/repositories/$DEFAULT_REPOSITORY_KEY
        fi

        sleep 3
        status_code=`curl -o /dev/null -s -w %{http_code} http://localhost:8081/artifactory/api/repositories/$ORIGINAL_DEFAULt_REPOSITORY`
        if [[ ${status_code} -eq 200 ]]; then
          curl -X DELETE -u admin:$NEW_INIT_PASSWORD -H "Content-type: application/json" http://localhost:8081/artifactory/api/repositories/$ORIGINAL_DEFAULt_REPOSITORY
        fi

        status_code=`curl -o /dev/null -s -w %{http_code}  -X POST -u admin:$NEW_INIT_PASSWORD -H "Content-type: application/json" -d "{\"key\": \"direct\", \"artifactoryAppContext\" : \"artifactory\", \"webServerType\" : \"DIRECT\", \"serverName\" : \"$NODE_IP\", \"artifactoryServerName\" : \"$NODE_IP\", \"artifactoryPort\" : 8081, \"dockerReverseProxyMethod\" : \"$DOCKER_REVERSE_PROXY_METHOD\", \"useHttps\" : false, \"useHttp\" : true, \"httpsPort\" : 443, \"httpPort\" : $NODE_PORT, \"upStreamName\" : \"artifactory\"}" http://localhost:8081/artifactory/api/system/configuration/webServer`

        touch $DONE_FLAG
      fi
      echo "Have been Up"
      exit 0;
    else
      echo "Not Up"
      exit 1;
    fi
