apiVersion: v1
kind: ConfigMap 
metadata:
  name: {{ template "artifactory.fullname" . }}
  labels:
    app: {{ template "artifactory.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.artifactory.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  ready_probe.sh: |
    #!/bin/bash

    curl --connect-timeout 2 localhost:8081/artifactory/webapp/#/login
    if [[ $? -eq 0 ]]; then
      curl -X POST -u admin:password -H "Content-type: application/json" -d "{ \"userName\" : \"admin\", \"oldPassword\" : \"password\", \"newPassword1\" : \"$NEW_INIT_PASSWORD\", \"newPassword2\" : \"$NEW_INIT_PASSWORD\" }" http://localhost:8081/artifactory/api/security/users/authorization/changePassword
      echo "Have been Up"
      exit 0;
    else
      echo "Not Up"
      exit 1;
    fi
